CDK app
lfucg/lfucg-exactions pull request #260
Opened 2024-06-04 17:25 UTC by benhavo

2024-06-06 12:02 UTC, chris-allen requested changes
One small thing, but otherwise this looks solid.

2024-06-06 12:02 UTC, chris-allen commented on cdk/cdk.context.json
> +  "availability-zones:account=651920002880:region=us-east-1": [
This shouldn't be here. You probably just ran `cdk diff` while auth'd with the wrong account. Delete this file and re-run `cdk diff --no-change-set`

2024-06-06 15:03 UTC, KellyInnovation approved these changes

2024-06-12 02:58 UTC, benhavo commented on cdk/cdk.context.json
> +  "availability-zones:account=651920002880:region=us-east-1": [
updated

2024-06-12 13:11 UTC, chris-allen commented
@benhavo Looks like this needs rebasing

2024-06-14 13:11 UTC, benhavo commented
> @benhavo Looks like this needs rebasing

@chris-allen Comments addressed

2024-06-14 13:19 UTC, chris-allen approved these changes

2024-06-17 13:22 UTC, merged